os:
  - linux
sudo: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

before_script:
  # Install the standalone Dart SDK
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  - sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
  - sudo apt-get update
  - sudo apt-get install dart
  - export PATH="$PATH:/usr/lib/dart/bin"

script:
  - ./ci-script.sh

cache:
  directories:
    - $HOME/.pub-cache
