os:
  - linux
sudo: true
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386
  - cd ~
  - wget https://dl.google.com/dl/android/studio/ide-zips/3.4.0.18/android-studio-ide-183.5452501-linux.tar.gz
  - tar -xvzf android-studio-ide-183.5452501-linux.tar.gz
  - export ANDROID_HOME=$HOME/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/tools
  - export PATH=$PATH:$ANDROID_HOME/platform-tools
  - yes | sdkmanager --licenses
  - cd $TRAVIS_BUILD_DIR

script:
  - ./ci-script.sh
